### ISSUE TITLE
Command 'journal.memo' not found At the every FIRST time of VS Code opening session.

### ISSUE THREAD

**Issue by xenogew** [pajoma/vscode-journal#35]
## Info
Windows OS 10 Pro 64 bits
VS Code 1.24.1
Journal v 0.6.0

## Issue Details
`Journal: Quick Memo` always throws exception and VS Code notify with message `Command 'journal.memo' not found` every first time I open VS Code, and then when I call command again, command will work properly by asking me to name a note.

## Steps
1.  Press F1 button
1.  type `memo`, then find the `Journal: Quick Memo` and then press Enter
1.  Boom, nothing happen, and notify balloon pop out with message `Command 'journal.memo' not found`

## Expected Behavior
*  Command will ask me to name a note at first time.

## Custom Settings
*  `"journal.base": "C:/ext/Natta/.vscode/journal",`

**Comment by pajoma** [comment]
Yes, I'm aware of this issue, it's kind of annoying. The extension activation is triggered by the first use of one of its commands. The alternative would be to activate it on startup of vscode, which I tried to avoid (to not influence the startup times of the whole application). 

I'll check if there's a workaround for this.

**Comment by pajoma** [comment]
See also https://github.com/Microsoft/vscode/issues/34913

**Comment by pajoma** [comment]
Ok, I don't see a workaround for this. Startup times for the journal extension is (on my computer) around ~15 ms, that shouldn't be the problem. But VSCode is lazily loading. Certain components like the editor are loaded much faster then the extension host (which activates the journal). There seems to be 1-2 seconds gap in which the commands are not accessible and you get the error message "command not found"

If your problem is not related to startup (meaning you wait a couple of seconds and you still get the error), then I am not able to reproduce. I did some improvements for the logging, will be publishing in the next few days.

**Comment by xenogew** [comment]
Even long time after start up the VS Code the error still thrown in my case. 

How can I help you to be more specific to the cause of problem?

I will collect the information you need and reply later.

**Comment by pajoma** [comment]
Hmm, can you send me the output for "Log (Extension Host)"?

**Comment by xenogew** [comment]
Nothing come out on the "OUTPUT" console for "Log (Extension Host)"

A little thing has changed, due to the latest update this morning, so I updated VS Code to version `1.25.0` and hope it might related to the problem I found.

Here's the link to view my screen shot after I reproduce to the "Step" I declared before.
[Screen shot](https://drive.google.com/file/d/1GoP2YF6fiU2Ha_ysoOoSkehgycJ3pzRh/view?usp=sharing)

Is there has another place to collect the log to specify the problem?

I will find out and update to you.

**Comment by pajoma** [comment]
This is strange, might be linked to a crashed extension host. Are commands of other extensions available. 

Can you please post the logs of the Developer Tools (Help -> Toggle Developer Tools)?

**Comment by xenogew** [comment]
Sorry for late reply, here's what you ask.

## Startup

```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1382 Error: Failed opening file C:\Users\ワンアピシット　ナッタサン\AppData\Roaming\Code\logs\20180709T104207\renderer1.log for writing: Invalid argument
    at RotatingLogger (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at Object.t.createSpdLogService (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1382:434)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5336:441
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5336:678
    at Object.K [as startup] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5338:235)
    at file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js:10:553
    at <anonymous>
t.createSpdLogService @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1382
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1376   ERR Error: Failed opening file c:\Users\ワンアピシット　ナッタサン\AppData\Roaming\Code\logs\20180709T104207\output_1_20180709T104209\tasks.log for writing: Invalid argument
    at RotatingLogger (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3379:318)
    at t.create (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:110:430)
    at e._createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1356:458)
    at e.createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1355:721)
    at t.instantiateChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3387:349)
    at t.createChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3386:445)
    at t.onDidRegisterChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3385:592)
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3384:403)
    at t.create (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:110:430)
    at e._createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1356:458)
    at e._createAndCacheServiceInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1357:403)
    at e._getOrCreateServiceInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1356:595)
    at e._createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1355:977)
    at e.createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1355:721)
    at e.createActionBarContributor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2282:33)
    at e.setInstantiationService (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2281:864)
    at t.initServices (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5276:39)
    at t.startup (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5268:494)
    at e.createWorkbench (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5322:66)
    at e.createContents (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5321:477)
    at e.open (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5329:989)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5338:28
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1376   ERR Error: Failed opening file c:\Users\ワンアピシット　ナッタサン\AppData\Roaming\Code\logs\20180709T104207\output_1_20180709T104209\extensions.log for writing: Invalid argument
    at RotatingLogger (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3379:318)
    at t.create (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:110:430)
    at e._createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1356:458)
    at e.createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1355:721)
    at t.instantiateChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3387:349)
    at t.createChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3386:445)
    at t.onDidRegisterChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3385:592)
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3384:403)
    at t.create (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:110:430)
    at e._createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1356:458)
    at e._createAndCacheServiceInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1357:403)
    at e._getOrCreateServiceInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1356:595)
    at e._createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1355:977)
    at e.createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1355:721)
    at e.createActionBarContributor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2282:33)
    at e.setInstantiationService (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2281:864)
    at t.initServices (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5276:39)
    at t.startup (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5268:494)
    at e.createWorkbench (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5322:66)
    at e.createContents (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5321:477)
    at e.open (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5329:989)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5338:28
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3147 [xabikos.JavaScriptSnippets]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue
w._logMessageInConsole @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3147
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] Error: Failed opening file C:\Users\ワンアピシット　ナッタサン\AppData\Roaming\Code\logs\20180709T104207\exthost1.log for writing: Invalid argument
    at RotatingLogger (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at Object.t.createSpdLogService (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:408:29)
    at new t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:453:241)
    at new t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:808:950)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:816:31
    at <anonymous>
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.smarty
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope text.html.javadoc
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1375  INFO standard startup Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1376   ERR Error: Failed opening file c:\Users\ワンアピシット　ナッタサン\AppData\Roaming\Code\logs\20180709T104207\output_1_20180709T104209\extension-output-#1.log for writing: Invalid argument
    at RotatingLogger (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3379:318)
    at t.create (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:110:430)
    at e._createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1356:458)
    at e.createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1355:721)
    at t.instantiateChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3387:349)
    at t.createChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3386:445)
    at t.onDidRegisterChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3385:592)
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:171:364)
    at e.registerChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2536:689)
    at e._getChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3419:446)
    at e.$append (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3419:103)
    at e._doInvokeHandler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3127:356)
    at e._invokeHandler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3127:74)
    at e._receiveRequest (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3126:164)
    at e._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3125:940)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3124:863
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3127:942
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:171:344)
    at c (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:302:1008)
    at Socket.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303:171)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is not loaded

t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] PHP process connected
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1376   ERR Error: Failed opening file c:\Users\ワンアピシット　ナッタサン\AppData\Roaming\Code\logs\20180709T104207\output_1_20180709T104209\extension-output-#3.log for writing: Invalid argument
    at RotatingLogger (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at new t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3379:318)
    at t.create (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:110:430)
    at e._createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1356:458)
    at e.createInstance (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1355:721)
    at t.instantiateChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3387:349)
    at t.createChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3386:445)
    at t.onDidRegisterChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3385:592)
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:171:364)
    at e.registerChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2536:689)
    at e._getChannel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3419:446)
    at e.$append (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3419:103)
    at e._doInvokeHandler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3127:356)
    at e._invokeHandler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3127:74)
    at e._receiveRequest (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3126:164)
    at e._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3125:940)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3124:863
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3127:942
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:171:344)
    at c (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:302:1008)
    at Socket.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303:171)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

## Call >> Quick Memo
```
log.ts:171   ERR Error: Failed opening file c:\Users\ワンアピシット　ナッタサン\AppData\Roaming\Code\logs\20180709T104207\output_1_20180709T104209\extension-output-#4.log for writing: Invalid argument
    at RotatingLogger (C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:16)
    at new t (outputServices.ts:226)
    at t.create (types.ts:166)
    at e._createInstance (instantiationService.ts:120)
    at e.createInstance (instantiationService.ts:73)
    at t.instantiateChannel (outputServices.ts:588)
    at t.createChannel (outputServices.ts:549)
    at t.onDidRegisterChannel (outputServices.ts:511)
    at e.fire (event.ts:142)
    at e.registerChannel (output.ts:179)
    at e._getChannel (mainThreadOutputService.ts:55)
    at e.$append (mainThreadOutputService.ts:38)
    at e._doInvokeHandler (rpcProtocol.ts:261)
    at e._invokeHandler (rpcProtocol.ts:246)
    at e._receiveRequest (rpcProtocol.ts:192)
    at e._receiveOneMessage (rpcProtocol.ts:174)
    at rpcProtocol.ts:107
    at rpcProtocol.ts:303
    at e.fire (event.ts:140)
    at c (ipc.net.ts:81)
    at Socket.<anonymous> (ipc.net.ts:108)
    at emitOne (events.js:96)
    at Socket.emit (events.js:191)
    at readableAddChunk (_stream_readable.js:178)
    at Socket.Readable.push (_stream_readable.js:136)
    at Pipe.onread (net.js:560)
console.ts:136 [Extension Host] [Journal] vscode-journal is starting!
notificationsAlerts.ts:40 Error: command 'journal.memo' not found
    at t._tryExecuteCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2915:36)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2914:846
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at l (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:45)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at l (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:45)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at e.resolveOk (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3060:806)
    at e._receiveReply (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3126:708)
    at e._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3126:6)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3124:863
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3127:942
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:171:344)
    at c (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:302:1008)
    at Socket.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303:171)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
e.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.error @ notificationService.ts:61
t.onError @ commandsHandler.ts:325
(anonymous) @ commandsHandler.ts:310
done @ winjs.base.js:1393
v @ winjs.base.js:1239
enter @ winjs.base.js:916
_run @ winjs.base.js:1083
_chainedError @ winjs.base.js:1046
n @ winjs.base.js:751
then @ winjs.base.js:1451
enter @ winjs.base.js:762
_run @ winjs.base.js:1083
_setCompleteValue @ winjs.base.js:1067
g @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
l @ winjs.base.js:1828
n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ winjs.base.js:1853
g @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
l @ winjs.base.js:1828
n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ winjs.base.js:1853
g @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
g @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
e.resolveOk @ lazyPromise.ts:65
e._receiveReply @ rpcProtocol.ts:222
e._receiveOneMessage @ rpcProtocol.ts:180
(anonymous) @ rpcProtocol.ts:107
(anonymous) @ rpcProtocol.ts:303
e.fire @ event.ts:140
c @ ipc.net.ts:81
(anonymous) @ ipc.net.ts:108
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
console.ts:136 [Extension Host] [Journal] Development Mode is enabled, Tracing in Console and Output is activated.
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```
