### ISSUE TITLE
Error opening/creating journal files over remote connection

### ISSUE THREAD

**Issue by jannek** [pajoma/vscode-journal#51]
If a remote development method is used (ssh in this case), new journal file creation gives an error, but apparently succeeds as subsequent access to file location works fine.

Repro:

- Open remote development connection to any Linux server over ssh with vscode-journal extension installed
- Ctrl+Shift+J -> Today

If file does not already exist, following error is logged:

    [09:58:07.054] [ERROR] 
    [09:58:07.059] [ERROR] Failed to process input. See Exception below.
    Error: cannot open vscode-remote://ssh-remote%2Bhost/path/to/Journal/2019/10/24.md. Detail: Unable to read file (Error: File not found (vscode-remote://ssh-remote+host/path/to/Journal/2019/10/24.md))
        at n.then.e (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4707:361)
        at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by jannek** [comment]
I expect the file to open on the remote server, not sure how to properly configure this.

Did you notice that the file is created after all on remote, and can be opened without errors next time?

**Comment by britlynch** [comment]
@jannek I am having the same issue. When I first try and open a new file, I get an error but after that if I try a second time it works without a problem. Hopefully this can be fixed because its a pain.

**Comment by spideyclick** [comment]
+1 I am also seeing the same issue. Here's what I see:

1. I hit CTRL  + Shift + J
2. Error pops up
3. After maybe 1 or 2 seconds, I see the file pop up in the file tree
4. I hit CTRL + Shift + J again
5. I get into my note for the day
6. I close the big error message and move on with my day

It's livable, but annoying enough that I thought I would comment on the issue and see if I could help. Thanks!

**Comment by lambdadade** [comment]
Same here. 
It works somehow, but the error code and the additional step to reopen the created file is annoying.
Would be nice to get some fix/workaround.

**Comment by pajoma** [comment]
## Spec

**Goal:** First-time entry/week/note creation on Remote SSH and WSL must open the file immediately with no error toast and no `[ERROR]` line in the Journal output channel.

**Why now:** Open since 2019, four users on this thread, and PLAN.md Phase 1.3 (`fs` → `vscode.workspace.fs`) is now done — the infrastructure to fix this cleanly is in place. The current UX is "press shortcut, see error, press again, it works" which is the first thing remote users hit on day one.

**Root cause (short version):** Three call sites (`Reader.loadEntryForDay`, `Reader.loadEntryForWeek`, `LoadNotes.loadNote`) speculatively call `vscode.workspace.openTextDocument` on a missing file and rely on catching the rejection. On a remote workspace that call surfaces a VS Code error notification independently of the catch, and the catch itself relies on prefix-matching the error message text — which is fragile and inconsistent across the three call sites.

**In scope:**
- Replace open-before-create with stat-first (`vscode.workspace.fs.stat` to test existence, then open OR create) at all three call sites.
- Remove the fragile error-message prefix matching.
- Regression tests asserting "no error logged" on the create path for entry, weekly, and notes.

**Out of scope:**
- Flattening the `new Promise((resolve, reject) => …)` wrappers around already-async code (PLAN.md Phase 2 owns this).
- Codespaces / dev containers (scoped to Remote SSH + WSL per discussion; the fix should cover them incidentally but they are not in the acceptance criteria).
- Any change to `Writer.createSaveLoadTextDocument` unless tests reveal a deeper issue.

**Acceptance:**
- `npm run check` clean.
- On Remote SSH: `Ctrl+Shift+J → Today`, weekly entry, and note creation each open the file on the first attempt, with no notification toast and no `[ERROR]` line. Same on WSL.
- Local behavior unchanged.

**Open questions:**
- Where the stat-existence helper lives (in `src/util/paths.ts` next to the existing `fs.stat` use, or inline). Will be decided in the plan step based on diff size.
- The non-`FileNotFound` branch (e.g. permission denied) must still reject loudly — the plan will spell out how stat-first preserves that.

**Related:** None across repos. No `blocked-by:` / `blocks:` labels needed.

**Detail:** [docs/specs/2026-05-14-fix-51-remote-file-creation.md](https://github.com/pajoma/vscode-journal/blob/51-error-openingcreating-journal-files-over-remote-connection/docs/specs/2026-05-14-fix-51-remote-file-creation.md)

---
Please reply `approved` / `lgtm` on this issue before I draft the plan.

**Comment by pajoma** [comment]
Accepted. 

Also cover the out of scope features.  Move from the old Promise to async/await.

Regarding the questions: 
- avoid inline, one file per module. 
- yes, error dialog required

**Comment by pajoma** [comment]
## Plan

**Approach:** Replace the speculative "open then catch failure" pattern with deterministic "stat first, then open OR create" in three methods (`Reader.loadEntryForDay`, `Reader.loadEntryForWeek`, `LoadNotes.loadNote`). A tiny `fileExists(uri)` helper in its own file wraps `vscode.workspace.fs.stat` and converts `FileSystemError.FileNotFound` to `false` — everything else propagates so VS Code can surface its own error dialog. The three methods also migrate from `new Promise((resolve, reject) => …)` wrappers to native `async/await` because the linear flow makes the wrappers dead weight.

**Trade-off:** Diff size grows from the Promise flattening, but the alternative (leave the wrappers, patch only the body) leaves a worse code shape behind. Limited to the three methods being changed; PLAN.md Phase 2 still owns the rest.

**Steps:**
1. Baseline `npm run check` on the branch.
2. Add failing regression tests covering the three flows (each asserts "file created, content correct, **no error logged**") — TDD.
3. Add the `fileExists` helper module + unit tests for missing/existing paths.
4. Refactor `Reader.loadEntryForDay` — drop the prefix-matching catch, flatten the Promise wrapper, gate on `fileExists`.
5. Refactor `Reader.loadEntryForWeek` — same shape; this is the worst-affected call site today (it only filters `cannot open file:`, not `cannot open vscode-remote:`).
6. Refactor `LoadNotes.loadNote` — same shape, no prefix check to drop because there isn't one.
7. `npm run check`; iterate.
8. Manual verification on Remote SSH + WSL Remote (entry, week, note); local regression check.
9. Open PR; update `CHANGELOG.md` and the `PLAN.md` Phase 1.3 note.

**Test scenarios:** 14 named in the plan doc — six integration tests in the Extension Host (entry/week/note × create/open-existing), two unit tests for the helper, six manual e2e checks (Remote SSH and WSL Remote × three actions, plus a local regression). The integration tests use a real `vscode.workspace.fs` and a capturing `TestLogger` so "no error logged" is a concrete assertion, not a vibe.

**Dependencies:** None. The branch already carries the merged #170 work.

**Risk:**
- Coupling on `FileSystemError.code === 'FileNotFound'` — covered by test S7 (missing-path returns `false`).
- Test environment can't easily simulate non-FileNotFound errors — that branch may end up only covered by the contract in the helper code itself. Documented as risk R4 in the plan.
- Removing the old `printError` call at `reader.ts:121` could hide a previously-logged error class — plan step 4 checks the upstream caller to confirm error surfacing still happens.

**Rollback:** Revert the squashed PR commit. No data migration, no config schema change. Pre-existing journal files are untouched.

**Related:** None (no cross-issue, no cross-repo).

**Detail:** [docs/plans/2026-05-14-fix-51-remote-file-creation.md](https://github.com/pajoma/vscode-journal/blob/51-error-openingcreating-journal-files-over-remote-connection/docs/plans/2026-05-14-fix-51-remote-file-creation.md)

---
Please reply `approved` / `lgtm` on this issue before I start implementation.

**Comment by pajoma** [comment]
PR #179 opens — implementing approved plan.
