### ISSUE TITLE
New Note dialog does nothing

### ISSUE THREAD

**Issue by niderhoff** [pajoma/vscode-journal#54]
Hello,

I just installed your extension and I really like the concept. I just noticed a bug. When I hit ctrl+shift+j and press create/select note, I get this exception (actually 2 exceptions)
```
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'replace' of undefined
$onExtensionRuntimeError | @ | mainThreadExtensionService.ts:65
-- | -- | --
   | _doInvokeHandler | @ | rpcProtocol.ts:398
   | _invokeHandler | @ | rpcProtocol.ts:383
   | _receiveRequest | @ | rpcProtocol.ts:299
   | _receiveOneMessage | @ | rpcProtocol.ts:226
   | (anonymous) | @ | rpcProtocol.ts:101
   | fire | @ | event.ts:582
   | fire | @ | ipc.net.ts:453
   | _receiveMessage | @ | ipc.net.ts:733
   | (anonymous) | @ | ipc.net.ts:592
   | fire | @ | event.ts:582
   | acceptChunk | @ | ipc.net.ts:239
   | (anonymous) | @ | ipc.net.ts:200
   | t | @ | ipc.net.ts:28
   | emit | @ | events.js:200
   | addChunk | @ | _stream_readable.js:294
   | readableAddChunk | @ | _stream_readable.js:275
   | Readable.push | @ | _stream_readable.js:210
   | onStreamRead | @ | internal/stream_base_commons.js:166
```

```
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'replace' of undefined
	at c:\Users\niid\.vscode\extensions\pajoma.vscode-journal-0.10.0\out\src\ext\vscode.js:172:48
	at _fulfilled (c:\Users\niid\.vscode\extensions\pajoma.vscode-journal-0.10.0\node_modules\q\q.js:854:54)
	at c:\Users\niid\.vscode\extensions\pajoma.vscode-journal-0.10.0\node_modules\q\q.js:883:30
	at Promise.promise.promiseDispatch (c:\Users\niid\.vscode\extensions\pajoma.vscode-journal-0.10.0\node_modules\q\q.js:816:13)
	at c:\Users\niid\.vscode\extensions\pajoma.vscode-journal-0.10.0\node_modules\q\q.js:624:44
	at runSingle (c:\Users\niid\.vscode\extensions\pajoma.vscode-journal-0.10.0\node_modules\q\q.js:137:13)
	at flush (c:\Users\niid\.vscode\extensions\pajoma.vscode-journal-0.10.0\node_modules\q\q.js:125:13)
	at processTicksAndRejections (internal/process/task_queues.js:82:9)
$onExtensionRuntimeError | @ | mainThreadExtensionService.ts:66
-- | -- | --
  | _doInvokeHandler | @ | rpcProtocol.ts:398
  | _invokeHandler | @ | rpcProtocol.ts:383
  | _receiveRequest | @ | rpcProtocol.ts:299
  | _receiveOneMessage | @ | rpcProtocol.ts:226
  | (anonymous) | @ | rpcProtocol.ts:101
  | fire | @ | event.ts:582
  | fire | @ | ipc.net.ts:453
  | _receiveMessage | @ | ipc.net.ts:733
  | (anonymous) | @ | ipc.net.ts:592
  | fire | @ | event.ts:582
  | acceptChunk | @ | ipc.net.ts:239
  | (anonymous) | @ | ipc.net.ts:200
  | t | @ | ipc.net.ts:28
  | emit | @ | events.js:200
  | addChunk | @ | _stream_readable.js:294
  | readableAddChunk | @ | _stream_readable.js:275
  | Readable.push | @ | _stream_readable.js:210
  | onStreamRead | @ | internal/stream_base_commons.js:166
```

Also the dialogbox that comes after does nothing and I cannot press enter etc.

**Comment by pajoma** [comment]
Yes, happens to me sometimes as well. Fix will be out soon.

**Comment by niderhoff** [comment]
Maybe it's related to me changing the journal folder location after I first installed the extension. (it grabbed the wrong location before I could change it).

I reinstalled the extension and it seems to work now.

**Comment by pajoma** [comment]
Fixed for now
